# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - echo "Creating fake Sphinx project so RTD is happy"
      - mkdir -p _rtd_dummy
      - echo "project = 'dummy'\nextensions = []" > _rtd_dummy/conf.py
      - mkdir -p _rtd_dummy/_build/html
      - echo "<html><body>placeholder</body></html>" > _rtd_dummy/_build/html/index.html
    post_build:
      - echo "Replacing Sphinx output with prebuilt pdoc HTML"
      - rm -rf _rtd_dummy/_build/html/*
      - cp -r docs/* _rtd_dummy/_build/html/
      - cp -r _rtd_dummy/_build/html/* $READTHEDOCS_OUTPUT/html/

sphinx:
  configuration: _rtd_dummy/conf.py
  