# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - echo "Dummy Sphinx config to satisfy RTD"
      - mkdir -p _rtd_dummy
      - echo "# dummy sphinx config" > _rtd_dummy/conf.py
    post_build:
      - echo "Copying prebuilt pdoc HTML docs"
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - cp -r docs/* $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: _rtd_dummy/conf.py
