# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T19:10:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class CardDto(BaseModel):
    code: str
    count: str
