# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T17:03:26+00:00

from __future__ import annotations

from pydantic import BaseModel


class MatchDto(BaseModel):
    pass


class TimelineDto(BaseModel):
    pass
