# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T19:10:06+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class PlayerDto(BaseModel):
    name: str
    rank: int
    lp: int = Field(..., description="League points.")


class LeaderboardDto(BaseModel):
    players: List[PlayerDto] = Field(
        ..., description="A list of players in Master tier."
    )
