# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T19:10:06+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class CardStatsDTO(BaseModel):
    energy: int
    might: int
    cost: int
    power: int


class CardArtDTO(BaseModel):
    thumbnail_url: str = Field(..., alias="thumbnailURL")
    full_url: str = Field(..., alias="fullURL")
    artist: str


class CardDTO(BaseModel):
    id: str = Field(..., description="Card ID")
    collector_number: int = Field(..., alias="collectorNumber")
    set: str
    name: str = Field(..., description="Card Name")
    description: str
    type: str = Field(..., description="Card Type")
    rarity: str
    faction: str
    stats: CardStatsDTO
    keywords: List[str]
    art: CardArtDTO
    flavor_text: str = Field(..., alias="flavorText")
    tags: List[str]


class SetDTO(BaseModel):
    id: str = Field(..., description="Set ID")
    name: str = Field(..., description="Set Name")
    cards: List[CardDTO]


class RiftboundContentDTO(BaseModel):
    game: str = Field(..., description="Game Name")
    version: str = Field(..., description="Content version")
    last_updated: str = Field(
        ..., alias="lastUpdated", description="ISO Timestamp of content last update"
    )
    sets: List[SetDTO]
