# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T17:03:26+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class SummonerDTO(BaseModel):
    profileIconId: int = Field(
        ..., description='ID of the summoner icon associated with the summoner.'
    )
    revisionDate: int = Field(
        ...,
        description='Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change.',
    )
    puuid: str = Field(
        ..., description='Encrypted PUUID. Exact length of 78 characters.'
    )
    summonerLevel: int = Field(
        ..., description='Summoner level associated with the summoner.'
    )
    id: Optional[str] = Field(
        None,
        description='Encrypted summoner ID. This field is deprecated and will be removed. Use `puuid` instead.',
    )
