# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-10-09T19:10:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LocalizedNamesDto(BaseModel):
    ar_ae: str = Field(..., alias='ar-AE')
    de_de: str = Field(..., alias='de-DE')
    en_gb: Optional[str] = Field(None, alias='en-GB')
    en_us: str = Field(..., alias='en-US')
    es_es: str = Field(..., alias='es-ES')
    es_mx: str = Field(..., alias='es-MX')
    fr_fr: str = Field(..., alias='fr-FR')
    id_id: str = Field(..., alias='id-ID')
    it_it: str = Field(..., alias='it-IT')
    ja_jp: str = Field(..., alias='ja-JP')
    ko_kr: str = Field(..., alias='ko-KR')
    pl_pl: str = Field(..., alias='pl-PL')
    pt_br: str = Field(..., alias='pt-BR')
    ru_ru: str = Field(..., alias='ru-RU')
    th_th: str = Field(..., alias='th-TH')
    tr_tr: str = Field(..., alias='tr-TR')
    vi_vn: str = Field(..., alias='vi-VN')
    zh_cn: str = Field(..., alias='zh-CN')
    zh_tw: str = Field(..., alias='zh-TW')


class ActDto(BaseModel):
    name: str
    localized_names: Optional[LocalizedNamesDto] = Field(
        None,
        alias='localizedNames',
        description='This field is excluded from the response when a locale is set',
    )
    id: str
    is_active: bool = Field(..., alias='isActive')
    parent_id: Optional[str] = Field(None, alias='parentId')
    type: Optional[str] = None


class ContentItemDto(BaseModel):
    name: str
    localized_names: Optional[LocalizedNamesDto] = Field(
        None,
        alias='localizedNames',
        description='This field is excluded from the response when a locale is set',
    )
    id: str
    asset_name: str = Field(..., alias='assetName')
    asset_path: Optional[str] = Field(
        None,
        alias='assetPath',
        description='This field is only included for maps and game modes. These values are used in the match response.',
    )


class ContentDto(BaseModel):
    version: str
    characters: List[ContentItemDto]
    maps: List[ContentItemDto]
    chromas: List[ContentItemDto]
    skins: List[ContentItemDto]
    skin_levels: List[ContentItemDto] = Field(..., alias='skinLevels')
    equips: List[ContentItemDto]
    game_modes: List[ContentItemDto] = Field(..., alias='gameModes')
    sprays: List[ContentItemDto]
    spray_levels: List[ContentItemDto] = Field(..., alias='sprayLevels')
    charms: List[ContentItemDto]
    charm_levels: List[ContentItemDto] = Field(..., alias='charmLevels')
    player_cards: List[ContentItemDto] = Field(..., alias='playerCards')
    player_titles: List[ContentItemDto] = Field(..., alias='playerTitles')
    acts: List[ActDto]
    ceremonies: Optional[List[ContentItemDto]] = None
    totems: Optional[List[ContentItemDto]] = None
