name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black pytest

      - name: Lint code
        run: black .

      - name: Run tests
        env:
            PYTHONPATH: ${{ github.workspace }}/pyke
        run: pytest --maxfail=1 --disable-warnings -v
