name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      TEST_PUUID: ${{ secrets.TEST_PUUID }}
      TEST_LEAGUE_ID: ${{ secrets.TEST_LEAGUE_ID }}
      TEST_CHALLENGE_ID: ${{ secrets.TEST_CHALLENGE_ID }}
      TEST_MATCH_ID: ${{ secrets.TEST_MATCH_ID }}
      TEST_TEAM_ID: ${{ secrets.TEST_TEAM_ID }}
      TEST_TOURNAMENT_ID: ${{ secrets.TEST_TOURNAMENT_ID }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] tox

      - name: Lint with Black
        run: black --check --diff .

      - name: Type check with mypy
        run: mypy --ignore-missing-imports --install-types --non-interactive .

      - name: Security scan with Bandit
        run: bandit -r src

      - name: Run tests via tox
        run: tox

  build-docs:
    runs-on: ubuntu-latest
    needs: lint-test-build
    if: ${{ success() }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] pdoc

      - name: Build Docs
        run: pdoc pyke -o docs

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
