name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        TEST_PUUID: ${{ secrets.TEST_PUUID }}
        TEST_LEAGUE_ID: ${{ secrets.TEST_LEAGUE_ID }}
        TEST_CHALLENGE_ID: ${{ secrets.TEST_CHALLENGE_ID }}
        TEST_MATCH_ID: ${{ secrets.TEST_MATCH_ID }}
        TEST_TEAM_ID: ${{ secrets.TEST_TEAM_ID }}
        TEST_TOURNAMENT_ID: ${{ secrets.TEST_TOURNAMENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black pytest mypy bandit pdoc

      - name: Lint code
        run: black .

      - name: Run tests
        env:
            PYTHONPATH: ${{ github.workspace }}/pyke
        run: pytest --maxfail=1 --disable-warnings -v

      - name: Mypy
        run: mypy --ignore-missing-imports --install-types .

      - name: Bandit
        run: bandit -r src

      - name: Build Docs
        run: pdoc pyke -o docs

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
